services:
  - type: web
    name: chez-nous-reseau-social
    env: node
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    scaling:
      minInstances: 1
      maxInstances: 1
